---
title: "4_2_figure2"
author: "Victor Yuan"
date: "25/11/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

# PMDs

```{r, message = FALSE, warning = FALSE}
# libraries and data
library(tidyverse); theme_set(theme_bw(base_size = 6))
library(glue)
library(scales)
library(DT)
library(viridisLite)
library(here)


base_path <- file.path("data", "main", "interim")

pDat <- readRDS(here(base_path, '2_3_pDat_contam.rds'))
pDat <- pDat %>%
  mutate(Tissue = case_when(
    !(Tissue %in% c('Villi', 'Villi maternal', 'Syncytiotrophoblast')) ~ paste(Tissue, 'cs'),
    Tissue == 'Syncytiotrophoblast' ~ 'Trophoblasts enz',
    TRUE ~ Tissue
  )) 


# raw methylation data
betas <- readRDS(here(base_path, '1_4_betas_noob_filt.rds'))
colnames(betas) <- pDat$Sample_Name

# annotation
anno <- readRDS('Z:/Victor/Repositories/EPIC_annotation/hg19_epic_annotation.rds')

#color code
color_code <- readRDS(here(base_path, '2_3_color_code.rds'))
color_code_tissue <- setNames(color_code$Colors_Tissue, color_code$label)

pDat_filt <- pDat %>% 
  filter(maternal_contamination_norm_flip < 0.35,
         !Sample_Name %in% c('PM364_hofb_cs', 'PL293_v_R2', 'PM366_vc_R2', 'P131_hofb_cs',
                             'PM324_V1', 'PM324_V4'),
         !Tissue %in% c('Villi maternal', 'Trophoblasts enz', 'Mixture cs', 'Dead Cells and Lymphocytes cs'))

# filter to first trimester
betas_filt <- betas[,pDat_filt$Sample_Name]

densities_pmds_plots <- readRDS(here(base_path, '2_7_pmd_density_plots.rds'))
coverage <- readRDS(here(base_path, '2_7_pmd_coverage.rds')) 
densities_high_res <- readRDS(here(base_path, '2_7_pmd_high_res_density.rds'))

#color code
color_code <- readRDS(here(base_path, '2_3_color_code.rds'))
color_code_tissue <- setNames(color_code$Colors_Tissue, color_code$label)

w1 <- 5.5
f1 <- 8
e1 <- TRUE
```

# PMD intervals

```{r, fig.height = 7}
p1 <- densities_high_res %>%
  # extract data
  filter(filt == 'filtered', array == 'EPIC') %>%
  
  # remove density coords
  select(Trimester, Celltype, range, prop) %>%
  distinct() %>%
  
  # widen
  pivot_wider(id_cols = c(Trimester, Celltype),
              names_from = range,
              values_from = prop) %>%
  # sum intervals
  mutate(`(0, 0.2]` = `(-Inf,0.1]` + `(0.1,0.2]`,
         `(0.2, 0.4]` = `(0.2,0.3]` + `(0.3,0.4]`,
         `(0.4, 0.6]` =  `(0.4,0.5]` + `(0.5,0.6]`,
         `(0.6, 0.8]` = `(0.6,0.7]` + `(0.7,0.8]`,
         `(0.8, 1]` =  `(0.8,0.9]` + `(0.9, Inf]`) %>%
  select(Trimester, Celltype, `(0, 0.2]`:`(0.8, 1]`) %>%
  pivot_longer(cols = c(`(0, 0.2]`:`(0.8, 1]`),
               names_to = 'range',
               values_to = 'prop') %>%
  
  {
    ggplot(data = ., aes(x = Trimester, y = prop, col = Celltype)) +
      geom_point(size = 0.9) +
      geom_line(aes(group = Celltype)) +
      facet_wrap(~range, ncol = 5,
                 labeller = labeller(
                   range = c('(0, 0.2]' = '0-20',
                             '(0.2, 0.4]' = '20-40',
                             '(0.4, 0.6]' = '40-60',
                             '(0.6, 0.8]' = '60-80',
                             '(0.8, 1]' = '80-100')
                 )) +
      scale_color_manual(values= color_code_tissue[unique(.$Celltype)],
                         labels = function(x)gsub(' cs', '', x)) +
      scale_x_discrete(labels = c('1', '2', '3')) +
      scale_y_continuous(expand = c(0, 0), 
                         limits = c(0, 0.56), 
                         breaks = seq(0,1, by = 0.1), 
                         labels = function(x)percent(x, accuracy = 1)) +
      labs(color = '', 
           #title = 'Percent of total CpGs',
           #subtitle = 'in different methylation intervals',
           y = '') +
      theme(legend.position = 'right',
            legend.text = element_text(size = 6),
            axis.ticks.x = element_blank(),
            strip.background = element_blank(),
            strip.text = element_text(face = 'bold', size = 5),
            panel.grid = element_blank(),
            
            panel.border = element_blank(),
            axis.line = element_line(color = 'black'))
  };p1
```

# PMD regions

```{r}
densities_pmds_plots <- readRDS(here(base_path, '2_7_pmd_density_plots.rds'))
coverage <- readRDS(here(base_path, '2_7_pmd_coverage.rds'))
densities_high_res <- readRDS(here(base_path, '2_7_pmd_high_res_density.rds'))
```

```{r}
# define plotting function
plot_region <- function(c, s, e, span = 0.1, cpg_size = NULL,
                        filtered = TRUE, array = 'EPIC') {
  
  # determine which cpgs to use, based on c, s, e
  if (is.null(cpg_size)) {
    cpg_size <- (e-s)*0.0005
  }
  
  # requires anno, betas_filt, anno_450k, pDat_filt
  if (filtered) {
    region1 <- anno %>%
      filter(chr == c, between(start, s, e),
             cpg %in% rownames(betas_filt),
             !cpg_id %in% c('island', 'shore'),
             !grepl('promoter', genes_id)) %>%
      pull(cpg)
  } else {
    region1 <- anno %>%
      filter(chr == c, between(start, s, e),
             cpg %in% rownames(betas_filt)) %>%
      pull(cpg)
  }
  
  if (array == '450K') {
    region1 <- intersect(anno_450k$Name, region1)
  } 
  
  # subset to betas to cpg in region, then make in plottable format
  region1_data <- betas_filt[region1, ] %>%
    
    t() %>%
    as.data.frame() %>%
    bind_cols(Sample_Name = rownames(.), .) %>%
    
    # melt
    gather(cpg, beta, -Sample_Name) %>%
    
    # add trimester and sex
    inner_join(pDat_filt %>% select(Sample_Name, Trimester, Tissue)) %>%
    
    # add cpg coordinates
    inner_join(anno %>% select(cpg, chr, pos = start)) %>%
    
    # set a grouping variable to control alpha for placenta/troph
    mutate(alpha_group = if_else(Tissue %in% c('Trophoblasts cs', 'Villi'),
                                 1, 0.6)) %>%
    
    # remove second trimester data
    filter(!Trimester %in% c('First', 'Second'))
  
  # get pmd start/end for plotting pmd track
  pmd_data <- anno %>%
    filter(chr == c, between(start, s, e), 
           !is.na(pmd_id)) %>%
    select(pmd_id) %>%
    separate(pmd_id, into = c('chr', 'start', 'end'), remove = FALSE) %>%
    mutate(chr = factor(chr, levels = paste0('chr', c(1:22, 'X'))),
           start = as.numeric(start),
           end = as.numeric(end)) %>%
    arrange(chr, start) %>%
    distinct()
  
  ggplot(region1_data) +
    
    # pmd track
    geom_rect(data = pmd_data, 
              aes(xmin = start, xmax = end), 
              ymin = 0, ymax = 1, fill = '#e8e8e8', alpha = 1) +
    
    # methylation track
    geom_line(stat = 'smooth', span = span, method = 'loess', se = FALSE,
              aes(x = pos, y = beta, color = Tissue, alpha = alpha_group)) +
    
    theme_bw(base_size = 6) +
    theme(panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.line = element_line(color = 'black')) +
    scale_color_manual(values= color_code_tissue[unique(region1_data$Tissue)],
                       labels = function(x)gsub(' cs', '', x),
                       guide = FALSE) +
    scale_y_continuous(expand = c(0,0), 
                       limits = c(0, 1), 
                       breaks = c(0, 0.25, 0.5, 0.75, 1), 
                       labels = function(x)percent(x, accuracy = 1)) +
    scale_x_continuous(limits = c(s, e), labels = function(x){x/10^6},
                       expand = c(0, 0)) +
    scale_alpha_identity() +
    labs(x = 'Position (Mbp)', y = 'DNA methylation',
         title = c, color = '')
}

p3 <- plot_region(c = 'chr4', s = 1500000, e = 8500000, 
            span = 0.07, filtered = FALSE, array = 'EPIC')

p2 <- plot_region(c = 'chr21', s = 25000000, e = 47000000, span = 0.05, filtered = T, #cpg_size = 5000,
            array = 'EPIC')
```

# mQTLs


```{r}
library(readxl)
dmcs_cell <- readRDS(here(base_path, '2_4_dmcs.rds'))
dmcs_and_mqtl_betas <- readRDS(here('data', 'main', 'interim', '2_9_dmcs_and_mqtls_betas.rds'))
fitvar_results <- readRDS(here('data', 'main', 'interim', '2_9_dmvs.rds'))
mqtls <- read_excel(here('data', 'external', 'journal.pgen.1007785.s018.xlsx'), skip = 1)
```

```{r}
# process betas
dmv_mqtl_dmc <- fitvar_results %>%
  left_join(dmcs_and_mqtl_betas %>%
              select(-bonferroni, -delta_b, -dmc_for_class) %>%
              distinct(), by = c('cpg' = 'cpg_id'))

plot_dmv <- function(data) {
  data %>%
    {
      ggplot(data = ., aes(x = Tissue, y= beta, color = Tissue)) +
        ggbeeswarm::geom_beeswarm(cex = 1.5,
                                  size = 0.05,
                                  priority = 'density',
                                  dodge.width = 0.3,
                                  fill = 'white',
                                  stroke = 1) +
        facet_wrap(~cpg, nrow = 2) +
        scale_color_manual(values = color_code_tissue[dmv_mqtl_dmc$Tissue],
                           guide = FALSE,
                           labels = function(x)gsub(' cs', '', x)) +
        scale_y_continuous(limits = c(0,1), labels = function(x)percent(x, accuracy = 1)) +
        theme_bw(base_size = 12) +
        theme(axis.text.x = element_blank(),
              axis.ticks = element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.minor.y = element_blank(),
              strip.background = element_blank()) +
        labs(x = '', y= 'DNA methylation', color = '') 
  }
}

# w: 4.5, h: 7, then resize manually down
p4 <- dmv_mqtl_dmc %>%
  arrange(cpg, Sample_Name) %>% 
  group_by(cpg) %>%
  filter(any(significant == '*' & direction == '-')) %>%
  
  select(-(DMV:direction)) %>%
  distinct() %>%
  
  group_by(Sample_Name) %>%
  arrange(cpg) %>%
  dplyr::slice(17:22) %>%
  plot_dmv();p4 

# w: 5, h: 5, resize down 1/2
p5 <- fitvar_results %>%
  mutate(negp = -p,
         significant = gsub('n.s. (fdr p > 0.01)', 'n.s. (FDR > 0.01)', significant)) %>%
  {
    ggplot(data = filter(., fdr < 0.01, abs(delta_b) > 0.5),
           aes(x = delta_b, y = p)) +
      geom_point(aes(color = DMV), alpha = 1, 
                 size = 1) +
      geom_point(data = filter(., fdr >= 0.01 | abs(delta_b) <= 0.5),
                 size = 1,
                 alpha = 0.2) +
      
      # add fdr p = 0.01 line
      geom_hline(data = group_by(., DMV) %>%
                   filter(fdr <= 0.01) %>%
                   arrange(desc(fdr)) %>%
                   summarize(threshold = max(p)),
                 linetype = 'dashed',
                 aes(yintercept = threshold)) +
      geom_vline(linetype = 'dashed', xintercept = 0.5) +
      geom_vline(linetype = 'dashed', xintercept = -0.5) + 
      
      facet_wrap(~DMV,
                 labeller = labeller(DMV = function(x)gsub(' cs', '', x))) +
      scale_x_continuous(labels = percent) +
      scale_y_continuous(trans = trans_new('neglog', 
                                           transform = function(x)(-log(x)), 
                                           inverse = function(x)(exp(-x)),
                                           breaks = log_breaks()),
                         label = function(x) scales::scientific_format()(x)) +
      scale_color_manual(values = color_code_tissue[fitvar_results$DMV],
                         guide = FALSE) +
      labs(x = 'Difference in variability (% methylation)', y = 'p-value',
           color = '', shape = '') +
      theme_bw(base_size = 14) +
      theme(strip.background = element_blank(),
            panel.grid = element_blank(),
            axis.text = element_text(size = 8),
            legend.position = 'top')
      
  };p5
```