---
title: "2_12_imprinting"
author: "Victor Yuan"
date: "07/01/2020"
output:
  html_document:
    keep_md: true
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
    theme: spacelab
    highlight: tango 
editor_options: 
  chunk_output_type: console
---

I previously looked at imprinting, but not in great detail. I also have since then compiled a list of imprinted regions and added these to the EPIC annotation.This script is for looking at imprints in more detail with this updated list of imprinted regions.


# Setup

## Libraries

```{r, message = FALSE, warning = FALSE}
# libraries and data
library(tidyverse)
library(scales)
library(here)
library(readxl)
library(janitor)
theme_set(theme_bw())
```

## Data

```{r eval = TRUE}
base_path <- file.path('data', 'main', 'interim')

# pData
pDat <- readRDS(here(base_path, '2_3_pDat_contam.rds'))
pDat <- pDat %>%
  mutate(Tissue = case_when(
    !(Tissue %in% c('Villi', 'Villi maternal', 'Syncytiotrophoblast')) ~ paste(Tissue, 'cs'),
    Tissue == 'Syncytiotrophoblast' ~ 'Trophoblasts enz',
    TRUE ~ Tissue
  )) 

# raw methylation data
betas <- readRDS(here(base_path, '1_4_betas_noob_filt.rds'))

# annotation
anno <- readRDS('Z:/Victor/Repositories/EPIC_annotation/hg19_epic_annotation.rds')
anno <- anno %>%
  as_tibble() %>%
  filter(cpg %in% rownames(betas)) # filter to filtered betas cpgs


# color key
color_code <- readRDS(here(base_path, '2_3_color_code.rds'))
color_code_tissue <- setNames(color_code$Colors_Tissue, color_code$label)
```

## Remove samples

```{r}
pDat_filt <- pDat %>% 
  filter(maternal_contamination_norm_flip < 0.35,
         !Sample_Name %in% c('PM364_hofb_cs', 'PL293_v_R2', 'PM366_vc_R2', 'P131_hofb_cs', 
                             'PM324_V4', 'PM324_V1', 'PM139_vc', 'PM77_vc'),
         !Tissue %in% c('Villi maternal', 'Trophoblasts enz', 'Mixture cs', 
                        'Dead Cells and Lymphocytes cs'),
         Trimester != 'Second')

betas_filt <- betas[,pDat_filt$Sentrix]
colnames(betas_filt) <- pDat_filt$Sample_Name
```

# Density

Calculate density

```{r}
# subset to imprinted cpgs
imprint_cpgs <- anno %>%
  filter(!is.na(imprint_sources)) %>%
  select(cpg, imprint_tissue_specificity, imprint_methylated_allele)

imprint_cpgs %>%
  count(imprint_tissue_specificity)
imprint_cpgs %>%
  count(imprint_tissue_specificity, imprint_methylated_allele)

# to calculate density we need betas and groups + cpg annotations
imprint_df <- betas_filt[imprint_cpgs$cpg,] %>%
  
  #tidy
  t() %>% 
  as.data.frame() %>%
  cbind(Sample_Name = rownames(.), .) %>%
  as_tibble() %>%
  
  pivot_longer(
    cols = -Sample_Name,
    names_to = 'cpg',
    values_to = 'beta'
  ) %>%
  
  # add tissue specificity
  left_join(imprint_cpgs) %>% 
  
  # add pData
  left_join(pDat_filt %>% select(Sample_Name, Tissue)) 
  
# calculate densities for ubiqutous vs placental
imprint_density <- imprint_df %>%
  group_by(imprint_tissue_specificity, Tissue ) %>% 
  select(-cpg, -imprint_methylated_allele) %>%
  summarize(p_25_75 = sum(beta > 0.25 & beta < 0.75)/length(beta),
            p_0_25 = sum(beta < 0.25)/length(beta),
            p_75_100 = sum(beta > 0.75)/length(beta),
            beta = list(beta)) %>% 
  
  # get sample names for each tissue
  mutate(
         densities = map(beta, ~ density(.)),
         x = map(densities, 'x'),
         y = map(densities, 'y')) %>%
 # remove input data
  select( Tissue, x, y, contains('p')) %>%
  unnest(cols = c(x, y))

imprint_density

# calculate densities for ubiqutous (mat) vs ubiquitous (pat)
imprint_density_allele <- imprint_df %>%
  filter(imprint_tissue_specificity == 'other') %>%
  group_by(imprint_methylated_allele, Tissue) %>% 
  select(-cpg, -imprint_tissue_specificity) %>%
  summarize(p_25_75 = sum(beta > 0.25 & beta < 0.75)/length(beta),
            p_0_25 = sum(beta < 0.25)/length(beta),
            p_75_100 = sum(beta > 0.75)/length(beta),
            beta = list(beta)) %>% 
  
  # get sample names for each tissue
  mutate(
         densities = map(beta, ~ density(.)),
         x = map(densities, 'x'),
         y = map(densities, 'y')) %>%
 # remove input data
  select( Tissue, x, y, contains('p')) %>%
  unnest(cols = c(x, y))
imprint_density_allele
```

Plot

```{r}
p1 <- imprint_density %>%
  {
    ggplot(data = ., aes(x = x, y = y, color = Tissue)) +
      geom_line(size = 1,) +
      geom_area(data = . %>%
                  filter(x < 0.75, x > 0.25),
                aes(fill = Tissue, color = NULL),
                alpha = 0.35) +
      geom_text(data = . %>%
                   select(Tissue, imprint_tissue_specificity, contains('p')) %>%
                   distinct() %>%
                   mutate(p_25_75 = scales::percent(p_25_75, accuracy = 1)),
                 x = 0.5,
                 y = 3.5,
                 aes(label = p_25_75),
                 show.legend = FALSE) +
      facet_grid(cols = vars(Tissue), 
                 rows = vars(imprint_tissue_specificity),
                 labeller = labeller(.cols = function(x)gsub(' cs', '', x)),
                 switch = 'both') +
      scale_color_manual(values = color_code_tissue[unique(imprint_density$Tissue)], 
                         na.value = '#636363',
                         guide = 'none') +
      scale_fill_manual(values = color_code_tissue[unique(imprint_density$Tissue)], 
                         na.value = '#636363',
                         labels = function(x)gsub(' cs', '', x),
                        guide = 'none') +
      scale_y_continuous(expand = c(0,0)) +
      scale_x_continuous(limits = c(0,1), 
                         expand = c(0,0), 
                         breaks = c(0, 0.25, 0.5, 0.75, 1), 
                         labels = c('', '', '50%', '', '100%')) +
      theme_bw(base_size = 12) +
      theme(panel.border = element_blank(),
            panel.grid = element_blank(),
            panel.spacing.x = unit(2, "mm"),
            strip.background = element_blank(),
            strip.placement = 'outside',
            strip.text.y = element_text(angle = 180),
            axis.line = element_line(),
            axis.title.y = element_text(angle = 0, vjust = 0.5)) +
      labs(x = 'DNA methylation', y = '', fill = '')+
      annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf)
  };p1

p2 <- imprint_density_allele %>%
  {
    ggplot(data = ., aes(x = x, y = y, color = Tissue)) +
      geom_line(size = 1,) +
      geom_area(data = . %>%
                  filter(x < 0.75, x > 0.25),
                aes(fill = Tissue, color = NULL),
                alpha = 0.35) +
      geom_text(data = . %>%
                   select(Tissue, imprint_methylated_allele, contains('p')) %>%
                   distinct() %>%
                   mutate(p_25_75 = scales::percent(p_25_75, accuracy = 1)),
                 x = 0.5,
                 y = 3.5,
                 aes(label = p_25_75),
                 show.legend = FALSE) +
      facet_grid(cols = vars(Tissue), 
                 rows = vars(imprint_methylated_allele),
                 labeller = labeller(.cols = function(x)gsub(' cs', '', x),
                                     .rows = c('M' = 'Maternal\n(# CpGs = 895)', 
                                               'P' = 'Paternal\n(# CpGs = 190)')),
                 switch = 'both') +
      scale_color_manual(values = color_code_tissue[unique(imprint_density$Tissue)], 
                         na.value = '#636363',
                         guide = 'none') +
      scale_fill_manual(values = color_code_tissue[unique(imprint_density$Tissue)], 
                         na.value = '#636363',
                         labels = function(x)gsub(' cs', '', x),
                        guide = 'none') +
      scale_y_continuous(expand = c(0,0), limits = c(0,4.9)) +
      scale_x_continuous(limits = c(0,1), 
                         expand = c(0,0), 
                         breaks = c(0, 0.25, 0.5, 0.75, 1), 
                         labels = c('', '', '50%', '', '100%')) +
      theme_bw(base_size = 12) +
      theme(panel.border = element_blank(),
            panel.grid = element_blank(),
            panel.spacing.x = unit(2, "mm"),
            strip.background = element_blank(),
            strip.placement = 'outside',
            strip.text.y = element_text(angle = 180),
            axis.line = element_line(),
            axis.title.y = element_text(angle = 0, vjust = 0.5)) +
      labs(x = 'DNA methylation', y = 'Methylated\nallele', fill = '')+
      annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf)
  };p2

```

# Save

```{r eval = FALSE}
saveRDS(imprint_density, here::here(base_path, '2_12_imprint_density.rds'))
imprint_density_allele %>% 
  saveRDS(here::here(base_path, '2_12_imprint_density_allele.rds'))
```