---
title: "2_5_correlation_first_third"
author: "Victor Yuan"
date: "26/07/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Setup

## Libraries

```{r}
# libraries and data
library(tidyverse)
library(viridis)
library(RColorBrewer)
library(kableExtra)
library(widyr)
```

## Data

```{r}
pDat <- readRDS('../../data/main/interim/2_3_pDat_contam.rds')
pDat <- pDat %>%
  mutate(Tissue = case_when(
    !(Tissue %in% c('Villi', 'Villi maternal', 'Syncytiotrophoblast')) ~ paste(Tissue, 'cs'),
    Tissue == 'Syncytiotrophoblast' ~ 'Trophoblasts enz',
    TRUE ~ Tissue
  )) 

# methylation data
betas <- readRDS('../../data/main/interim/1_4_betas_noob_filt.rds')

mset_noob <- readRDS('../../data/main/interim/1_4_mset_noob.rds') # for mvals
colnames(mset_noob) <- colnames(betas) <- pDat$Sample_Name
mvals <- getM(mset_noob)


# filter samples
pDat_filt <- pDat %>% 
  filter(maternal_contamination_norm_flip < 0.35,
         !Sample_Name %in% c('PM364_hofb_cs', 'PL293_v_R2', 'PM366_vc_R2', 'P131_hofb_cs'),
         !Tissue %in% c('Villi maternal', 'Trophoblasts enz', 'Mixture cs', 'Dead Cells and Lymphocytes cs'))

mvals_filt <- mvals[rownames(betas),pDat_filt$Sample_Name]
betas_filt <- betas[,pDat_filt$Sample_Name]


# annotation
anno <- getAnnotation(mset_noob)
anno <- anno %>%
  as_tibble() %>%
  filter(Name %in% rownames(betas)) # filter to filtered betas cpgs
probe_anno <- readRDS('../../data/main/interim/1_1_probe_anno.rds')

# color key
pheatmap_color_code <- readRDS('../../data/main/interim/1_1_color_code.rds')

color_code <- readRDS('../../data/main/interim/2_3_color_code.rds')
color_code_tissue <- setNames(color_code$Colors_Tissue, color_code$label)
```


# Correlation

```{r}
pDat_filt
table(pDat_filt$Tissue, pDat_filt$Trimester)

# calculate means
cell_mean <- pDat_filt %>% 
  select(Tissue, Trimester, Sample_Name) %>%
  group_by(Tissue, Trimester) %>%
  
  # nest, calculate means, unnest
  summarize(Sample_Names = list(Sample_Name)) %>%
  mutate(mean_meth = map(Sample_Names, ~ enframe(rowMeans(betas_filt[,.]), 
                                                 name = 'cpg', value = 'mean_meth'))) %>%
  unnest(mean_meth) %>% 
  mutate(key = paste0(Trimester, '-', Tissue)) %>%
  ungroup() %>%
  select(-Tissue, -Trimester) %>%
  spread(key = key, value = mean_meth)

cell_calcs <- expand.grid(colnames(cell_mean)[-1], colnames(cell_mean)[-1]) %>% as_tibble %>%
  mutate_at(c('Var1', 'Var2'), as.character) %>%
  filter(str_extract(Var1, 'First|Second|Third') != str_extract(Var2, 'First|Second|Third')) %>%
  mutate(diff = map2(Var1, Var2, ~ tibble(cpg = cell_mean$cpg, 
                                          diff = cell_mean[[.x]] -
                                            cell_mean[[.y]],
                                          mean_meth_a = cell_mean[[.x]],
                                          mean_meth_b = cell_mean[[.y]])),
         cor = map2_dbl(Var1, Var2, ~ cor(cell_mean[,.x], cell_mean[,.y]))) %>%
  separate(Var1, into = c('Trimester_a', 'Tissue_a'), sep = '-') %>%
  separate(Var2, into = c('Trimester_b', 'Tissue_b'), sep = '-') %>%
  unnest(diff)


# hex plot
cell_calcs %>%
  filter(Trimester_a == 'First', Trimester_b == 'Third') %>%
  mutate(key_a = paste0(Trimester_a, ' - ', Tissue_a),
         key_b = paste0(Trimester_b, ' - ', Tissue_b)) %>% 
  {
    ggplot(data = ., aes(x = mean_meth_a, y = mean_meth_b)) +
      geom_hex() +
      geom_label(data = . %>% select(key_a, key_b, Trimester_a:cor) %>% distinct(),
                 aes(x = 0.8, y = 0.075,
                 label = paste0("italic(r)==", prettyNum(cor, digits = 2))),
                 parse = T, hjust = 0, size = 3) +
      facet_grid(key_a ~ key_b)  +
      scale_fill_viridis_c(trans = 'log10', 
                           breaks = c(1, 10, 100, 1000, 10000, 100000, 1000000), 
                           labels =scales::trans_format('log10',scales::math_format(10^.x)))
           
    }

#correlogram
cell_calcs %>%
    filter(Trimester_a == 'First', Trimester_b == 'Third') %>%
    mutate(key_a = paste0(Trimester_a, ' - ', Tissue_a),
           key_b = paste0(Trimester_b, ' - ', Tissue_b)) %>% 
  select(key_a, key_b, Trimester_a:cor) %>% 
  distinct() %>%
  ggplot(aes(x = key_a, y = key_b, fill = cor)) +
  geom_tile() +
  geom_text(aes(label  = prettyNum(cor, digits = 2)), color = 'white') +
  coord_equal(expand = F) +
  scale_fill_viridis_c(limits = c(NA, 1)) 

```
